name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cfspeedtest
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}

  docker-build-and-push:
    needs: [create-release, upload-assets]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Buildx cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image for amd64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: |
            cybuerg/cfspeedtest:${{ github.ref_name }}-amd64
            cybuerg/cfspeedtest:latest-amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-amd64,mode=max
          
      - name: Build and push Docker image for arm64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          tags: |
            cybuerg/cfspeedtest:${{ github.ref_name }}-arm64
            cybuerg/cfspeedtest:latest-arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-arm64,mode=max
          
      - name: Create and push multi-platform manifest
        run: |
          docker manifest create cybuerg/cfspeedtest:${{ github.ref_name }} \
            cybuerg/cfspeedtest:${{ github.ref_name }}-amd64 \
            cybuerg/cfspeedtest:${{ github.ref_name }}-arm64
          docker manifest create cybuerg/cfspeedtest:latest \
            cybuerg/cfspeedtest:latest-amd64 \
            cybuerg/cfspeedtest:latest-arm64
          docker manifest push cybuerg/cfspeedtest:${{ github.ref_name }}
          docker manifest push cybuerg/cfspeedtest:latest
          
      - name: Merge and move cache
        run: |
          mkdir -p /tmp/.buildx-cache-new
          cp -r /tmp/.buildx-cache-amd64/* /tmp/.buildx-cache-new/ || true
          cp -r /tmp/.buildx-cache-arm64/* /tmp/.buildx-cache-new/ || true
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
